---
title: "Lab 2 - Intro to data"
author: "Name here"
date: "Date of lab session"
output: 
  html_document: 
    fig_height: 4
    theme: simplex
    highlight: haddock
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

* * *

## Lab report

#### Load data:
```{r}
load(url("https://github.com/GarciaRios/govt_3990/raw/gh-pages/Labs/lab2/Data/cdc.RData"))
```



```{r}
names(cdc)
str(cdc)
```

This is  who you plot a histogram

```{r}
ggplot(cdc, aes(x = age )) +
  geom_histogram(binwidth = 1)


```

```{r}
cdc %>% summary()
```

```{r}
cdc %>% 
  select(age) %>% 
  summary()
```

```{r}
cdc %>% 
  select(weight, wtdesire) %>% 
  summary() 

```


```{r}
cdc %>% 
  summarise(mean_wt = mean(weight), 
            sd_wt = sd(weight),
            mean_ht = mean(height), 
            sd_ht = sd(height))



```


```{r}
cdc %>% 
  select(genhlth) %>% 
  summary()
  


cdc %>% 
  select(gender, smoke100) %>% 
  table() %>% 
  prop.table(.,2)
```



#### Exercise 1: 



```{r ex1}

```

#### Exercise 2: 



```{r ex2}

```

#### Exercise 3: 



```{r ex3}

```

#### Exercise 4: 



```{r ex4}

```

#### Exercise 5: 



```{r ex5}

```

#### Exercise 6: 



```{r ex6}

```


* * *

### On your own:

#### 1:



```{r oyo1}

```

#### 2:



```{r oyo2}

```

#### 3:



```{r oyo3}

```

#### 4:

 

```{r oyo4}

```

#### 5:



```{r oyo5}

```

* * *
