---
title: "Lab 6 - More inference for numerical data"
author: "Name"
date: "Date of lab session"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: simplex
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
library(dplyr)
library(ggplot2)
```

* * *

## Lab report

#### Load data:
```{r load-data}
load(url("https://github.com/GarciaRios/govt_3990/raw/gh-pages/Labs/lab6/acs.RData"))
```

#### Load inference:
```{r load-inference}
load(url("https://github.com/GarciaRios/govt_3990/raw/gh-pages/Labs/lab5/inference.RData"))
```


## Exercises:

#### Exercise 1: 

```{r ex1}

```

#### Exercise 2: 


```{r ex2}

```


#### Exercise 3: 

```{r ex3}

```


#### Exercise 4: 


```{r ex4}

```


#### Exercise 5: 

```{r ex5}

```

#### Exercise 6:

```{r ex6}

```

#### Exercise 7:

```{r ex7}

```

#### Exercise 8:

```{r ex8}

```


* * *

## On your own:

#### 1: 


```{r oyo1}

```


#### 2: 

```{r oyo2}

```


#### 3:

```{r oyo 3}

```


#### 4:


```{r oyo4}


```


#### 5:

```{r oyo5}


```

#### 6:

```{r oyo6}


```


#### 7:

```{r oyo7}


```

